server {
    listen 80;

    # Uma pasta local (O arquivo HTML parado no disco)
    location /ping {
        alias /usr/share/nginx/html/monitor-262/;
        index index.html;
    }

    # Uma pasta local (O arquivo HTML parado no disco)
    location /strings-lab {
        alias /usr/share/nginx/html/afinador/;
        index index.html;
    }

    # Vem de @app.get("/status") no main.py
    location /status {
        proxy_pass http://monitor-service:8000/status;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # Ajustado para bater com o @app.websocket("/audio") do Python
    location /audio {
        proxy_pass http://audio-service:8001/audio;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
    }
}