server {
    listen 80;

    # Uma pasta local (O arquivo HTML parado no disco)
    # / depois de ping pra indicar que é pasta
    location /ping/ {
        alias /usr/share/nginx/html/monitor-262/;
        index index.html;
    }

    # @app.get("/status") no /home/caio/apps/monitor-262/api/main.py
    # sem / depois de status pois é uma rota, não pasta
    location /status {
        proxy_pass http://monitor-service:8000/status;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}