server {
    listen 80;
    server_name localhost;

    # INTERFACE (O visual do Software)
    # location sem a barra final para permitir o redirecionamento automático
    location /ping {
        # alias indica a pasta interna onde você chumbou o HTML
        alias /usr/share/nginx/html/monitor-262/;
        index index.html;

        # O "Plano de Busca": tenta o arquivo ($uri), depois a pasta ($uri/), 
        # e se não achar nada, carrega o index.html (evita o 404)
        try_files $uri $uri/ /index.html;
    }

    # @app.get("/status") em /home/caio/apps/monitor-262/api/main.py
    # API (O motor em Python)
    # O seu Javascript (index.html) deve buscar os dados em /status
    location /status {
        proxy_pass http://monitor-service:8000/status;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # REDIRECIONAMENTO DE RAIZ (Opcional)
    # Se você digitar apenas "localhost", ele te joga direto para o /ping
    location = / {
        return 301 /ping;
    }
}